//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsblCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsblCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        internal static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBL Check.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип аутентификации:.
        /// </summary>
        internal static string AUTH_TYPE {
            get {
                return ResourceManager.GetString("AUTH_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите.
        /// </summary>
        internal static string BUSY_INDICATOR_DEFAULT_CAPTION {
            get {
                return ResourceManager.GetString("BUSY_INDICATOR_DEFAULT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружается разработка. Пожалуйста, подождите.
        /// </summary>
        internal static string BUSY_INDICATOR_LOAD_DEVELOPMENT_CAPTION {
            get {
                return ResourceManager.GetString("BUSY_INDICATOR_LOAD_DEVELOPMENT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить активную вкладку.
        /// </summary>
        internal static string CHECK_ACTIVE_TAB {
            get {
                return ResourceManager.GetString("CHECK_ACTIVE_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить все.
        /// </summary>
        internal static string CHECK_ALL {
            get {
                return ResourceManager.GetString("CHECK_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить открытые вкладки.
        /// </summary>
        internal static string CHECK_OPENED_TABS {
            get {
                return ResourceManager.GetString("CHECK_OPENED_TABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить выбранный элемент.
        /// </summary>
        internal static string CHECK_SELECTED_ITEM {
            get {
                return ResourceManager.GetString("CHECK_SELECTED_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты.
        /// </summary>
        internal static string COMMON_REPORTS {
            get {
                return ResourceManager.GetString("COMMON_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вычисление.
        /// </summary>
        internal static string COMPONENT_CALCULATION {
            get {
                return ResourceManager.GetString("COMPONENT_CALCULATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключение установлено успешно..
        /// </summary>
        internal static string CONNECTION_SUCCESS {
            get {
                return ResourceManager.GetString("CONNECTION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Ошибок.
        /// </summary>
        internal static string COUNT_ERRORS {
            get {
                return ResourceManager.GetString("COUNT_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Сообщений.
        /// </summary>
        internal static string COUNT_MESSAGES {
            get {
                return ResourceManager.GetString("COUNT_MESSAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Предупреждений.
        /// </summary>
        internal static string COUNT_WARNINGS {
            get {
                return ResourceManager.GetString("COUNT_WARNINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий документ.
        /// </summary>
        internal static string CURRENT_DOCUMENT {
            get {
                return ResourceManager.GetString("CURRENT_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to База данных:.
        /// </summary>
        internal static string DATABASE {
            get {
                return ResourceManager.GetString("DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер:.
        /// </summary>
        internal static string DATABASE_SOURCE {
            get {
                return ResourceManager.GetString("DATABASE_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диалоги.
        /// </summary>
        internal static string DIALOGS {
            get {
                return ResourceManager.GetString("DIALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы карточек электронных документов.
        /// </summary>
        internal static string DOCUMENT_CARD_TYPES {
            get {
                return ResourceManager.GetString("DOCUMENT_CARD_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя компоненты....
        /// </summary>
        internal static string ENTER_COMPONENT_NAME {
            get {
                return ResourceManager.GetString("ENTER_COMPONENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка чтения базы данных. Пожалуйста проверьте параметры подключения..
        /// </summary>
        internal static string ERROR_DATABASE_READ {
            get {
                return ResourceManager.GetString("ERROR_DATABASE_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка чтения каталога с разработкой..
        /// </summary>
        internal static string ERROR_FOLDER_READ {
            get {
                return ResourceManager.GetString("ERROR_FOLDER_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка чтения пакета разработки. Пожалуйста проверьте корректность выгруженного пакета разработки..
        /// </summary>
        internal static string ERROR_PACKAGE_READ {
            get {
                return ResourceManager.GetString("ERROR_PACKAGE_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспортировать как CSV.
        /// </summary>
        internal static string EXPORT_AS_CSV {
            get {
                return ResourceManager.GetString("EXPORT_AS_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт успешно завершен.
        /// </summary>
        internal static string EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым..
        /// </summary>
        internal static string FIELD_COULD_NOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("FIELD_COULD_NOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        internal static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string FUNCTION_HELP {
            get {
                return ResourceManager.GetString("FUNCTION_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функции.
        /// </summary>
        internal static string FUNCTIONS {
            get {
                return ResourceManager.GetString("FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализация.
        /// </summary>
        internal static string INITIALIZATION {
            get {
                return ResourceManager.GetString("INITIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интегрированные отчеты.
        /// </summary>
        internal static string INTEGRATED_REPORTS {
            get {
                return ResourceManager.GetString("INTEGRATED_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Isbl {
            get {
                object obj = ResourceManager.GetObject("Isbl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управляемые папки.
        /// </summary>
        internal static string MANAGED_FOLDERS {
            get {
                return ResourceManager.GetString("MANAGED_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string MESSAGE_CODE {
            get {
                return ResourceManager.GetString("MESSAGE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Столбец.
        /// </summary>
        internal static string MESSAGE_COLUMN {
            get {
                return ResourceManager.GetString("MESSAGE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string MESSAGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MESSAGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        internal static string MESSAGE_DOCUMENT {
            get {
                return ResourceManager.GetString("MESSAGE_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка.
        /// </summary>
        internal static string MESSAGE_LINE {
            get {
                return ResourceManager.GetString("MESSAGE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серъёзность.
        /// </summary>
        internal static string MESSAGE_SEVERITY {
            get {
                return ResourceManager.GetString("MESSAGE_SEVERITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть все.
        /// </summary>
        internal static string OPEN_ALL {
            get {
                return ResourceManager.GetString("OPEN_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть базу данных....
        /// </summary>
        internal static string OPEN_DATABASE {
            get {
                return ResourceManager.GetString("OPEN_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть базу данных.
        /// </summary>
        internal static string OPEN_DATABASE_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("OPEN_DATABASE_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть каталог с разработкой....
        /// </summary>
        internal static string OPEN_FOLDER {
            get {
                return ResourceManager.GetString("OPEN_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть пакет разработки....
        /// </summary>
        internal static string OPEN_PACKAGE {
            get {
                return ResourceManager.GetString("OPEN_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытые документы.
        /// </summary>
        internal static string OPENED_DOCUMENTS {
            get {
                return ResourceManager.GetString("OPENED_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        internal static string OPTIONS {
            get {
                return ResourceManager.GetString("OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Версия: {1}..
        /// </summary>
        internal static string PRODUCT_NAME_VERSION {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последние.
        /// </summary>
        internal static string RECENT {
            get {
                return ResourceManager.GetString("RECENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы справочников.
        /// </summary>
        internal static string REFERENCE_TYPES {
            get {
                return ResourceManager.GetString("REFERENCE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string REFRESH {
            get {
                return ResourceManager.GetString("REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список ошибок.
        /// </summary>
        internal static string REPORT_VIEWER {
            get {
                return ResourceManager.GetString("REPORT_VIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блоки типовых маршрутов.
        /// </summary>
        internal static string ROUTE_BLOCKS {
            get {
                return ResourceManager.GetString("ROUTE_BLOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сценарии.
        /// </summary>
        internal static string SCRIPTS {
            get {
                return ResourceManager.GetString("SCRIPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проводник.
        /// </summary>
        internal static string SOURCE_EXPLORER {
            get {
                return ResourceManager.GetString("SOURCE_EXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типовые маршруты.
        /// </summary>
        internal static string STANDARD_ROUTES {
            get {
                return ResourceManager.GetString("STANDARD_ROUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пуск.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовая страница.
        /// </summary>
        internal static string START_PAGE {
            get {
                return ResourceManager.GetString("START_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить подключение.
        /// </summary>
        internal static string TEST_CONNECTION {
            get {
                return ResourceManager.GetString("TEST_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя:.
        /// </summary>
        internal static string USER_NAME {
            get {
                return ResourceManager.GetString("USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        internal static string VIEW {
            get {
                return ResourceManager.GetString("VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBL Check.
        /// </summary>
        internal static string WINDOWS_TITLE {
            get {
                return ResourceManager.GetString("WINDOWS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мастера действий.
        /// </summary>
        internal static string WIZARDS {
            get {
                return ResourceManager.GetString("WIZARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены неверные данные для подключения. Пожалуйста проверьте парамертры подключения..
        /// </summary>
        internal static string WRONG_DATABASE_CREDENTIALS {
            get {
                return ResourceManager.GetString("WRONG_DATABASE_CREDENTIALS", resourceCulture);
            }
        }
    }
}
