//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsblCheck.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IsblCheck.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить сборку &quot;{0}&quot;..
        /// </summary>
        internal static string ERROR_COULD_NOT_LOAD_ASSEMBLY {
            get {
                return ResourceManager.GetString("ERROR_COULD_NOT_LOAD_ASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки контекста приложения..
        /// </summary>
        internal static string ERROR_LOAD_APP_CONTEXT {
            get {
                return ResourceManager.GetString("ERROR_LOAD_APP_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки контекста разработки..
        /// </summary>
        internal static string ERROR_LOAD_DEV_CONTEXT {
            get {
                return ResourceManager.GetString("ERROR_LOAD_DEV_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контекст приложения успешно загружен..
        /// </summary>
        internal static string INFO_LOAD_APP_CONTEXT {
            get {
                return ResourceManager.GetString("INFO_LOAD_APP_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контекст разработки успешно загружен..
        /// </summary>
        internal static string INFO_LOAD_DEV_CONTEXT {
            get {
                return ResourceManager.GetString("INFO_LOAD_DEV_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сборка &quot;{0}&quot; успешно загружена..
        /// </summary>
        internal static string INFO_RULES_ASSEMBLY_LOADED {
            get {
                return ResourceManager.GetString("INFO_RULES_ASSEMBLY_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка &quot;{0}&quot; со сборками успешно загружена..
        /// </summary>
        internal static string INFO_RULES_FOLDER_LOADED {
            get {
                return ResourceManager.GetString("INFO_RULES_FOLDER_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синтаксическое дерево для &quot;{0}&quot;: {1}..
        /// </summary>
        internal static string TRACE_SYNTAX_TREE {
            get {
                return ResourceManager.GetString("TRACE_SYNTAX_TREE", resourceCulture);
            }
        }
    }
}
